version: "3"

services:
  frontend:
    image: node:20
    container_name: frontend
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    tty: true
    command: npm run dev